### ISSUE TITLE
convert.js error

### ISSUE THREAD

**Issue by shootybangman** [GDColon/MC2GD#4]
I went into Minecraft and ran `/functions scripts:find` and everything looked fine. But when I ran `MC2GD.bat`, it said:
`TypeError: Cannot read property '1' of null
    at C:\Users\sebas\Downloads\MC2GD-master\MC2GD-master\convert.js:77:54
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)`
Any idea what this might mean?

**Comment by jusnash** [comment]
Yeah, im having this problem too.

**Comment by jusnash** [comment]
You found a way to fix it yet?

**Comment by rozbrajaczpoziomow** [comment]
Seems like convert.js cannot find the `Dimension: [...]` line in the log file.
Propably logs file changed on newer versions of the game.
cc/ @GDColon
